alias alacritty='flatpak-spawn --host alacritty'
alias fastfetch='flatpak-spawn --host fastfetch'
alias btrfs='flatpak-spawn --host btrfs'
alias rpm-ostree='flatpak-spawn --host rpm-ostree'
alias flatpak='flatpak-spawn --host flatpak'
alias firefox='flatpak-spawn --host firefox'
alias btop='flatpak-spawn --host btop'
alias podman='flatpak-spawn --host podman'
