format = """
[](fg:blue)\
$python\
$conda\
$lua\
[](fg:blue bg:bright-black)\
$directory\
[](fg:bright-black bg:bright-green)\
$git_branch\
$git_status\
[ ](bg:bright-green)\
[](fg:bright-green bg:bright-black)\
$golang\
$helm\
$java\
$docker_context\
$openstack\
$kubernetes\
$all
"""

right_format="""
$cmd_duration\
[❮](fg:yellow bg:3f3f3f)\
$time\
"""

[character] # The name of the module we are configuring is 'character'
success_symbol = "[❯❯](fg:yellow bg:3f3f3f)"
error_symbol = "[❯❯](fg:red bg:3f3f3f)"

[status]
disabled = false

[python]
format = """
[${symbol}${version}${pyenv_prefix}]($style)\
[ ($virtualenv)](fg:black bg:blue)\
"""
symbol = " "
version_format = "${major}.${minor}"
style = "fg:white bold bg:blue"

[conda]
format = "[$symbol$environment]($style)"
style = "fg:black bg:blue"

[lua]
format = "[lua ${symbol}(${version})]($style)"
style = "fg:white bold bg:blue"

[directory]
format = "[ $path ]($style)[$read_only]($read_only_style)" 
repo_root_format = """
[ $before_root_path]($before_repo_root_style)\
[$repo_root ]($repo_root_style)\
[$path]($style)[$read_only]($read_only_style)\
"""
truncate_to_repo = false
truncation_length = 5
repo_root_style = "fg:white bold bg:bright-black"
# use_os_path_sep = false
style = "fg:yellow bg:bright-black"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

# Default git invokes in $all
# $git_branch\
# $git_commit\
# $git_state\
# $git_metrics\
# $git_status\

[git_branch]
format = "[ $symbol $branch (:$remote_branch) ]($style)"
symbol = ""
style = "fg:black bg:bright-green"

[git_status]
format = """
([($stashed)]($style))\
([\\[($conflicted)\\]](fg:black bold bg:red))\
([\\[($modified)($renamed)($untracked)($deleted)\\]](fg:white bold bg:red))\
([\\[($staged)\\]](fg:bright-black bold bg:bright-yellow))\
([\\[$ahead_behind\\]]($style))\
"""
conflicted = ''
modified = ''
deleted = ''
ahead = '↑${count}'
diverged = '↕${ahead_count}⇣${behind_count}'
behind = '↓${count}'
# windows_starship = '/cygdrive/c/Program Files/starship/bin/starship.exe'
style = "fg:black bg:bright-green"

[cmd_duration]
format = "[ $duration ]($style)"
style = "fg:yellow bg:3f3f3f"

[time]
format = "[ $time ]($style)"
disabled = false
time_format = "%a %T"
style = "fg:yellow bg:3f3f3f"

[shell]
format = "[$indicator]($style)" 
powershell_indicator = ""
bash_indicator = '$'
fish_indicator = ''
# fish_indicator = ''
disabled = false
style = "fg:black bold bg:bright-yellow"

# [custom.fish_vi_mode_prompt]
# format = "[$output]($style)"
# command = "fish_default_mode_prompt"
# shell = ["C:\\cygwin64\\bin\\fish.exe"]
# os = "windows"
# style = "fg:white bold"

[docker_context]
format = '\[[$symbol$context]($style)\]'

[kubernetes]
format = '\[[$symbol$context( [\($namespace\)](fg:#AF7AC5))]($style)\]'
disabled = false

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'
