[colors.vi_mode_cursor]
cursor = "#ff00ff"

[font]
size = 14.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Shift|Control"

[[mouse.bindings]]
action = "Copy"
mouse = "Middle"

[[mouse.bindings]]
action = "Paste"
mods = "Control"
mouse = "Middle"

[[mouse.bindings]]
action = "ExpandSelection"
mouse = "Right"

[window]
decorations = "none"
opacity = 0.75

[window.padding]
x = 8
y = 8
